#NovaMobs ConfigFile
#Disabled Worlds 
worldsSpawnDisabled: 
- Lobby
#Animal a Monsters spawning
spawn-animals: true
spawn-mobs: true
#Spawning Settings (20ticks = 1s)
autoSpawnTime: 20
MINSPAWN_RADIUS: 15
MAXSPAWN_RADIUS: 20
maxSpawns_Animals: 10
maxSpawns_Mobs: 10
maxSpawns_NetherMobs: 5
spawnAnimals: true
spawnMobs: true
spawnNethermobs: true
#Config Settings
ConfigVersion: "1.0"#Do not Remove or Edit!